import Header from "../components/header";
import WorkspaceSection from "../components/workspace-section";
import SidebarContainer from "../components/sidebar-container";
import AddContainer from "../components/add-container";
import CardContainer from "../components/card-container";
import CardForm from "../components/card-form";
import FormContainer from "../components/form-container";
import DeleteContainer from "../components/delete-container";
import styles from "./delete.module.css";

const Delete = () => {
  return (
    <div className={styles.delete}>
      <Header
        groupImageUrl="../group-1953.svg"
        groupImageUrl195="../group-2013.svg"
      />
      <div className={styles.deleteChild} />
      <WorkspaceSection
        groupSvgText="../group-241.svg"
        groupSvgText2423="../group-2423.svg"
      />
      <SidebarContainer
        arrowIconUrl="icondouble-arrow3.svg"
        dashboardIconUrl="../icondashboad3.svg"
        calendarIconUrl="iconcalendar3.svg"
        socialMediaIconUrl="../iconsocial-media3.svg"
        analyticsIconUrl="../iconanalytic2.svg"
        dotIconUrl="dot-01-xs-112.svg"
        userLeadIconUrl="../iconuser-lead79.svg"
        dotIcon1Url="dot-01-xs-112.svg"
        userStarIconUrl="iconuserstar79.svg"
        notificationIconUrl="iconnotifications3.svg"
        dotIcon1Url2="dot-01-xs-112.svg"
        documentIconUrl="icondocuments3.svg"
        dotIcon2Url="dot-01-xs-112.svg"
        segmentIconUrl="iconsegments3.svg"
        checkIconUrl="../iconfile-check76.svg"
      />
      <AddContainer
        sortByText="(3)"
        sortByIconUrl="../iconsort-by18.svg"
        userLeadIconUrl="../iconuser-lead80.svg"
        userStarText="iconuserstar80.svg"
        checkIconUrl="../iconfile-check77.svg"
        descriptionText="icondescription73.svg"
        messageText="iconmessage73.svg"
        checklistIconUrl="iconchecklist-373.svg"
        iconLinkText="iconlink73.svg"
        ellipseText="../ellipse-82.svg"
        agentBookText="ContactRM"
        userLeadIconUrl2="../iconuser-lead81.svg"
        userStarText2="iconuserstar80.svg"
        checkIconUrl2="../iconfile-check78.svg"
        descriptionText2="icondescription73.svg"
        messageIconUrl="iconmessage73.svg"
        checklistIconText="iconchecklist-373.svg"
        iconLinkText2="iconlink73.svg"
        closeText="iconclose6.svg"
        propTop="172px"
        propLeft="230px"
        propJustifyContent="flex-start"
        propGap="89px"
        propDisplay="none"
        propDisplay1="unset"
        propDisplay2="unset"
      />
      <CardContainer
        completionStatus="Completed "
        sortIconUrl="../iconsort-by18.svg"
        userLeadIconUrl="../iconuser-lead82.svg"
        userStarIconUrl="iconuserstar82.svg"
        descriptionIconUrl="icondescription73.svg"
        messageIconUrl="iconmessage73.svg"
        checklistIconUrl="iconchecklist-373.svg"
        iconLinkUrl="iconlink73.svg"
        propTop="172px"
        propLeft="848px"
        propDisplay="unset"
      />
      <CardForm
        statusText="In Review "
        sortIconUrl="../iconsort-by18.svg"
        statusIconUrl="../ellipse-82.svg"
        teamName="ContactRM"
        userLeadIconUrl="../iconuser-lead83.svg"
        userStarIconUrl="iconuserstar80.svg"
        checkIconUrl="../iconfile-check79.svg"
        taskName="Design a website"
        iconDescriptionText="icondescription73.svg"
        messageIconUrl="iconmessage73.svg"
        checklistIconUrl="iconchecklist-373.svg"
        iconLinkUrl="iconlink73.svg"
        ellipseIconUrl="../ellipse-82.svg"
        contactRMText="ContactRM"
        userLeadIconText="../iconuser-lead84.svg"
        userStarText="iconuserstar80.svg"
        checkIconText="../iconfile-check80.svg"
        taskDescriptionText="Design a website"
        iconDescriptionText2="icondescription73.svg"
        messageIconText="iconmessage73.svg"
        checklistIconText="iconchecklist-373.svg"
        iconLinkText="iconlink73.svg"
        ellipseIconText="../ellipse-82.svg"
        agentBookText="ContactRM"
        userLead6Text="../iconuser-lead85.svg"
        userStarText2="iconuserstar80.svg"
        check5IconText="../iconfile-check81.svg"
        designTaskText="Design a website"
        iconDescriptionText3="icondescription73.svg"
        messageIcon2Url="iconmessage73.svg"
        checklist3IconUrl="iconchecklist-373.svg"
        iconLink2Text="iconlink73.svg"
        contactRMText2="ContactRM"
        userLead7Text="../iconuser-lead86.svg"
        userStar4Text="iconuserstar80.svg"
        check6IconText="../iconfile-check82.svg"
        designTaskDescriptionText="Design a website"
        iconDescriptionUrl="icondescription73.svg"
        messageIcon2Text="iconmessage73.svg"
        checklist3IconText="iconchecklist-373.svg"
        iconLink2Text2="iconlink73.svg"
        ellipseIconText2="../ellipse-82.svg"
        agentBookText2="ContactRM"
        userLead8Text="../iconuser-lead87.svg"
        userStar4Text2="iconuserstar80.svg"
        check7IconText="../iconfile-check83.svg"
        designTaskTitle="Design a website"
        iconDescriptionUrl2="icondescription73.svg"
        message2IconText="iconmessage73.svg"
        checklist3IconText2="iconchecklist-373.svg"
        iconLink2Text3="iconlink73.svg"
        propLeft="694px"
        propTop="172px"
        propJustifyContent="flex-start"
        propGap="89px"
        propDisplay1="unset"
        propDisplay7="none"
        propDisplay8="unset"
        propDisplay14="none"
        propDisplay15="unset"
        propDisplay22="unset"
      />
      <CardForm
        statusText="To Do"
        sortIconUrl="../iconsort-by18.svg"
        statusIconUrl="../ellipse-82.svg"
        teamName="Development"
        userLeadIconUrl="../iconuser-lead88.svg"
        userStarIconUrl="iconuserstar80.svg"
        checkIconUrl="../iconfile-check84.svg"
        taskName="Develope a app for the Zaan Corporation"
        iconDescriptionText="icondescription73.svg"
        messageIconUrl="iconmessage73.svg"
        checklistIconUrl="iconchecklist-373.svg"
        iconLinkUrl="iconlink73.svg"
        ellipseIconUrl="../ellipse-82.svg"
        contactRMText="Asteler.io"
        userLeadIconText="iconuser-lead89.svg"
        userStarText="iconuserstar80.svg"
        checkIconText="../iconfile-check85.svg"
        taskDescriptionText="Develope a app for the Zaan Corporation"
        iconDescriptionText2="icondescription73.svg"
        messageIconText="iconmessage73.svg"
        checklistIconText="iconchecklist-373.svg"
        iconLinkText="iconlink73.svg"
        ellipseIconText="../ellipse-82.svg"
        agentBookText="Zaan Corp"
        userLead6Text="../iconuser-lead90.svg"
        userStarText2="iconuserstar80.svg"
        check5IconText="../iconfile-check86.svg"
        designTaskText="Develope a app for the Zaan Corporation"
        iconDescriptionText3="icondescription73.svg"
        messageIcon2Url="iconmessage73.svg"
        checklist3IconUrl="iconchecklist-373.svg"
        iconLink2Text="iconlink73.svg"
        contactRMText2="Zaan Corp"
        userLead7Text="../iconuser-lead91.svg"
        userStar4Text="iconuserstar80.svg"
        check6IconText="../iconfile-check87.svg"
        designTaskDescriptionText="Develope a app for the Zaan Corporation"
        iconDescriptionUrl="icondescription73.svg"
        messageIcon2Text="iconmessage73.svg"
        checklist3IconText="iconchecklist-373.svg"
        iconLink2Text2="iconlink73.svg"
        ellipseIconText2="../ellipse-82.svg"
        agentBookText2="Zaan Corp"
        userLead8Text="../iconuser-lead92.svg"
        userStar4Text2="iconuserstar80.svg"
        check7IconText="../iconfile-check88.svg"
        designTaskTitle="Develope a app for the Zaan Corporation"
        iconDescriptionUrl2="icondescription73.svg"
        message2IconText="iconmessage73.svg"
        checklist3IconText2="iconchecklist-373.svg"
        iconLink2Text3="iconlink73.svg"
        propLeft="384px"
        propTop="172px"
        propDisplay1="unset"
        propDisplay4="flex"
        propDisplay5="flex"
        propDisplay6="flex"
        propDisplay7="none"
        propDisplay8="unset"
        propDisplay11="flex"
        propDisplay12="flex"
        propDisplay13="flex"
        propDisplay14="none"
        propDisplay15="unset"
        propDisplay18="flex"
        propDisplay19="flex"
        propDisplay20="flex"
        propDisplay22="unset"
        propDisplay25="flex"
        propDisplay26="flex"
        propDisplay27="flex"
        propDisplay31="flex"
        propDisplay32="flex"
        propDisplay33="flex"
      />
      <FormContainer
        iconSortBy="../iconsort-by18.svg"
        iconUserLead="../iconuser-lead93.svg"
        iconUserstar="iconuserstar80.svg"
        iconFileCheck="../iconfile-check89.svg"
        iconMessage="iconmessage73.svg"
        iconChecklist3="iconchecklist-373.svg"
        iconLink="iconlink73.svg"
        iconUserLead1="../iconuser-lead94.svg"
        iconUserstar1="iconuserstar80.svg"
        iconFileCheck1="../iconfile-check90.svg"
        iconMessage1="iconmessage73.svg"
        iconChecklist31="iconchecklist-373.svg"
        iconLink1="iconlink73.svg"
        iconUserLead2="../iconuser-lead95.svg"
        iconUserstar2="iconuserstar80.svg"
        iconFileCheck2="../iconfile-check91.svg"
        iconMessage2="iconmessage73.svg"
        iconChecklist32="iconchecklist-373.svg"
        iconLink2="iconlink73.svg"
        iconUserLead3="../iconuser-lead96.svg"
        iconUserstar3="iconuserstar80.svg"
        iconFileCheck3="../iconfile-check92.svg"
        iconMessage3="iconmessage73.svg"
        iconChecklist33="iconchecklist-373.svg"
        iconLink3="iconlink73.svg"
        iconUserLead4="../iconuser-lead97.svg"
        iconUserstar4="iconuserstar80.svg"
        iconFileCheck4="../iconfile-check93.svg"
        iconMessage4="iconmessage73.svg"
        iconChecklist34="iconchecklist-373.svg"
        iconLink4="iconlink73.svg"
        iconUserLead5="../iconuser-lead98.svg"
        iconUserstar5="iconuserstar80.svg"
        iconFileCheck5="../iconfile-check94.svg"
        iconMessage5="iconmessage73.svg"
        iconChecklist35="iconchecklist-373.svg"
        iconLink5="iconlink73.svg"
        iconUserLead6="../iconuser-lead99.svg"
        iconUserstar6="iconuserstar80.svg"
        iconFileCheck6="../iconfile-check95.svg"
        iconMessage6="iconmessage92.svg"
        iconChecklist36="iconchecklist-392.svg"
        iconLink6="iconlink92.svg"
        iconUserLead7="../iconuser-lead100.svg"
        iconUserstar7="iconuserstar80.svg"
        iconFileCheck7="../iconfile-check96.svg"
        iconMessage7="iconmessage92.svg"
        iconChecklist37="iconchecklist-392.svg"
        iconLink7="iconlink92.svg"
        iconUserLead8="../iconuser-lead101.svg"
        iconUserstar8="iconuserstar80.svg"
        iconFileCheck8="../iconfile-check97.svg"
        iconMessage8="iconmessage92.svg"
        iconChecklist38="iconchecklist-392.svg"
        iconLink8="iconlink92.svg"
        iconUserLead9="../iconuser-lead102.svg"
        iconUserstar9="iconuserstar80.svg"
        iconFileCheck9="../iconfile-check98.svg"
        iconMessage9="iconmessage92.svg"
        iconChecklist39="iconchecklist-392.svg"
        iconLink9="iconlink92.svg"
        iconUserLead10="../iconuser-lead103.svg"
        iconUserstar10="iconuserstar80.svg"
        iconFileCheck10="../iconfile-check99.svg"
      />
      <div className={styles.panOut}>
        <div className={styles.panOutChild} />
        <img
          className={styles.chevronDown1Icon}
          alt=""
          src="../chevrondown-1.svg"
        />
      </div>
      <div className={styles.deleteItem} />
      <div className={styles.deleteConfirmation}>
        <DeleteContainer />
      </div>
    </div>
  );
};

export default Delete;
