import Header from "../components/header";
import WorkspaceSection from "../components/workspace-section";
import SidebarContainer from "../components/sidebar-container";
import AddContainer from "../components/add-container";
import CardContainer from "../components/card-container";
import CardForm from "../components/card-form";
import FormContainer from "../components/form-container";
import SavedContainer from "../components/saved-container";
import ContainerSection from "../components/container-section";
import styles from "./save-filter.module.css";

const SaveFilter = () => {
  return (
    <div className={styles.saveFilter}>
      <img className={styles.bgIcon} alt="" src="../bg1.svg" />
      <Header
        groupImageUrl="../group-1955.svg"
        groupImageUrl195="group-2015.svg"
      />
      <div className={styles.saveFilterChild} />
      <WorkspaceSection
        groupSvgText="../group-2412.svg"
        groupSvgText2423="group-2425.svg"
      />
      <SidebarContainer
        arrowIconUrl="icondouble-arrow4.svg"
        dashboardIconUrl="../icondashboad5.svg"
        calendarIconUrl="iconcalendar4.svg"
        socialMediaIconUrl="../iconsocial-media5.svg"
        analyticsIconUrl="../iconanalytic.svg"
        dotIconUrl="dot-01-xs-116.svg"
        userLeadIconUrl="../iconuser-lead104.svg"
        dotIcon1Url="dot-01-xs-116.svg"
        userStarIconUrl="iconuserstar104.svg"
        notificationIconUrl="iconnotifications4.svg"
        dotIcon1Url2="dot-01-xs-116.svg"
        documentIconUrl="icondocuments4.svg"
        dotIcon2Url="dot-01-xs-116.svg"
        segmentIconUrl="../iconsegments.svg"
        checkIconUrl="../iconfile-check124.svg"
      />
      <AddContainer
        sortByText="(3)"
        sortByIconUrl="iconsort-by23.svg"
        userLeadIconUrl="../iconuser-lead130.svg"
        userStarText="iconuserstar105.svg"
        checkIconUrl="../iconfile-check125.svg"
        descriptionText="icondescription73.svg"
        messageText="iconmessage96.svg"
        checklistIconUrl="iconchecklist-396.svg"
        iconLinkText="iconlink96.svg"
        ellipseText="../ellipse-82.svg"
        agentBookText="ContactRM"
        userLeadIconUrl2="../iconuser-lead131.svg"
        userStarText2="iconuserstar105.svg"
        checkIconUrl2="../iconfile-check126.svg"
        descriptionText2="icondescription73.svg"
        messageIconUrl="iconmessage96.svg"
        checklistIconText="iconchecklist-396.svg"
        iconLinkText2="iconlink96.svg"
        closeText="../iconclose.svg"
        propTop="172px"
        propLeft="230px"
        propJustifyContent="flex-start"
        propGap="89px"
        propDisplay="none"
        propDisplay1="unset"
        propDisplay2="unset"
      />
      <CardContainer
        completionStatus="Completed "
        sortIconUrl="../iconsort-by29.svg"
        userLeadIconUrl="../iconuser-lead132.svg"
        userStarIconUrl="iconuserstar132.svg"
        descriptionIconUrl="icondescription73.svg"
        messageIconUrl="../iconmessage121.svg"
        checklistIconUrl="../iconchecklist-3121.svg"
        iconLinkUrl="iconlink121.svg"
        propTop="172px"
        propLeft="848px"
        propDisplay="unset"
      />
      <CardForm
        statusText="In Review "
        sortIconUrl="iconsort-by30.svg"
        statusIconUrl="../ellipse-82.svg"
        teamName="ContactRM"
        userLeadIconUrl="../iconuser-lead133.svg"
        userStarIconUrl="iconuserstar133.svg"
        checkIconUrl="../iconfile-check127.svg"
        taskName="Design a website"
        iconDescriptionText="icondescription73.svg"
        messageIconUrl="iconmessage122.svg"
        checklistIconUrl="iconchecklist-3122.svg"
        iconLinkUrl="iconlink96.svg"
        ellipseIconUrl="../ellipse-82.svg"
        contactRMText="ContactRM"
        userLeadIconText="iconuser-lead134.svg"
        userStarText="iconuserstar133.svg"
        checkIconText="../iconfile-check128.svg"
        taskDescriptionText="Design a website"
        iconDescriptionText2="icondescription73.svg"
        messageIconText="iconmessage122.svg"
        checklistIconText="iconchecklist-3122.svg"
        iconLinkText="iconlink96.svg"
        ellipseIconText="../ellipse-82.svg"
        agentBookText="ContactRM"
        userLead6Text="../iconuser-lead135.svg"
        userStarText2="iconuserstar133.svg"
        check5IconText="../iconfile-check129.svg"
        designTaskText="Design a website"
        iconDescriptionText3="icondescription73.svg"
        messageIcon2Url="iconmessage122.svg"
        checklist3IconUrl="iconchecklist-3122.svg"
        iconLink2Text="iconlink96.svg"
        contactRMText2="ContactRM"
        userLead7Text="../iconuser-lead136.svg"
        userStar4Text="iconuserstar133.svg"
        check6IconText="../iconfile-check130.svg"
        designTaskDescriptionText="Design a website"
        iconDescriptionUrl="icondescription73.svg"
        messageIcon2Text="iconmessage122.svg"
        checklist3IconText="iconchecklist-3122.svg"
        iconLink2Text2="iconlink96.svg"
        ellipseIconText2="../ellipse-82.svg"
        agentBookText2="ContactRM"
        userLead8Text="../iconuser-lead137.svg"
        userStar4Text2="iconuserstar133.svg"
        check7IconText="../iconfile-check131.svg"
        designTaskTitle="Design a website"
        iconDescriptionUrl2="icondescription73.svg"
        message2IconText="iconmessage122.svg"
        checklist3IconText2="iconchecklist-3122.svg"
        iconLink2Text3="iconlink96.svg"
        propLeft="694px"
        propTop="172px"
        propJustifyContent="flex-start"
        propGap="89px"
        propDisplay1="unset"
        propDisplay7="none"
        propDisplay8="unset"
        propDisplay14="none"
        propDisplay15="unset"
        propDisplay22="unset"
      />
      <CardForm
        statusText="To Do"
        sortIconUrl="iconsort-by23.svg"
        statusIconUrl="../ellipse-82.svg"
        teamName="Development"
        userLeadIconUrl="../iconuser-lead138.svg"
        userStarIconUrl="iconuserstar105.svg"
        checkIconUrl="../iconfile-check132.svg"
        taskName="Develope a app for the Zaan Corporation"
        iconDescriptionText="icondescription73.svg"
        messageIconUrl="iconmessage96.svg"
        checklistIconUrl="iconchecklist-396.svg"
        iconLinkUrl="iconlink96.svg"
        ellipseIconUrl="../ellipse-82.svg"
        contactRMText="Asteler.io"
        userLeadIconText="../iconuser-lead139.svg"
        userStarText="iconuserstar105.svg"
        checkIconText="../iconfile-check133.svg"
        taskDescriptionText="Develope a app for the Zaan Corporation"
        iconDescriptionText2="icondescription73.svg"
        messageIconText="iconmessage96.svg"
        checklistIconText="iconchecklist-396.svg"
        iconLinkText="iconlink96.svg"
        ellipseIconText="../ellipse-82.svg"
        agentBookText="Zaan Corp"
        userLead6Text="../iconuser-lead140.svg"
        userStarText2="iconuserstar105.svg"
        check5IconText="../iconfile-check134.svg"
        designTaskText="Develope a app for the Zaan Corporation"
        iconDescriptionText3="icondescription73.svg"
        messageIcon2Url="iconmessage96.svg"
        checklist3IconUrl="iconchecklist-396.svg"
        iconLink2Text="iconlink96.svg"
        contactRMText2="Zaan Corp"
        userLead7Text="../iconuser-lead141.svg"
        userStar4Text="iconuserstar105.svg"
        check6IconText="../iconfile-check135.svg"
        designTaskDescriptionText="Develope a app for the Zaan Corporation"
        iconDescriptionUrl="icondescription73.svg"
        messageIcon2Text="iconmessage96.svg"
        checklist3IconText="iconchecklist-396.svg"
        iconLink2Text2="iconlink96.svg"
        ellipseIconText2="../ellipse-82.svg"
        agentBookText2="Zaan Corp"
        userLead8Text="../iconuser-lead142.svg"
        userStar4Text2="iconuserstar105.svg"
        check7IconText="../iconfile-check136.svg"
        designTaskTitle="Develope a app for the Zaan Corporation"
        iconDescriptionUrl2="icondescription73.svg"
        message2IconText="iconmessage96.svg"
        checklist3IconText2="iconchecklist-396.svg"
        iconLink2Text3="iconlink96.svg"
        propLeft="384px"
        propTop="172px"
        propDisplay1="unset"
        propDisplay4="flex"
        propDisplay5="flex"
        propDisplay6="flex"
        propDisplay7="none"
        propDisplay8="unset"
        propDisplay11="flex"
        propDisplay12="flex"
        propDisplay13="flex"
        propDisplay14="none"
        propDisplay15="unset"
        propDisplay18="flex"
        propDisplay19="flex"
        propDisplay20="flex"
        propDisplay22="unset"
        propDisplay25="flex"
        propDisplay26="flex"
        propDisplay27="flex"
        propDisplay31="flex"
        propDisplay32="flex"
        propDisplay33="flex"
      />
      <FormContainer
        iconSortBy="iconsort-by32.svg"
        iconUserLead="../iconuser-lead143.svg"
        iconUserstar="iconuserstar105.svg"
        iconFileCheck="../iconfile-check137.svg"
        iconMessage="iconmessage122.svg"
        iconChecklist3="iconchecklist-3122.svg"
        iconLink="iconlink96.svg"
        iconUserLead1="../iconuser-lead144.svg"
        iconUserstar1="iconuserstar105.svg"
        iconFileCheck1="../iconfile-check138.svg"
        iconMessage1="iconmessage122.svg"
        iconChecklist31="iconchecklist-3122.svg"
        iconLink1="iconlink96.svg"
        iconUserLead2="../iconuser-lead145.svg"
        iconUserstar2="iconuserstar105.svg"
        iconFileCheck2="../iconfile-check139.svg"
        iconMessage2="iconmessage122.svg"
        iconChecklist32="iconchecklist-3122.svg"
        iconLink2="iconlink96.svg"
        iconUserLead3="../iconuser-lead146.svg"
        iconUserstar3="iconuserstar105.svg"
        iconFileCheck3="../iconfile-check140.svg"
        iconMessage3="iconmessage122.svg"
        iconChecklist33="iconchecklist-3122.svg"
        iconLink3="iconlink96.svg"
        iconUserLead4="../iconuser-lead147.svg"
        iconUserstar4="iconuserstar105.svg"
        iconFileCheck4="../iconfile-check141.svg"
        iconMessage4="iconmessage122.svg"
        iconChecklist34="iconchecklist-3122.svg"
        iconLink4="iconlink96.svg"
        iconUserLead5="../iconuser-lead148.svg"
        iconUserstar5="iconuserstar105.svg"
        iconFileCheck5="../iconfile-check142.svg"
        iconMessage5="iconmessage122.svg"
        iconChecklist35="iconchecklist-3122.svg"
        iconLink5="iconlink96.svg"
        iconUserLead6="../iconuser-lead149.svg"
        iconUserstar6="iconuserstar105.svg"
        iconFileCheck6="../iconfile-check143.svg"
        iconMessage6="iconmessage138.svg"
        iconChecklist36="iconchecklist-3138.svg"
        iconLink6="iconlink138.svg"
        iconUserLead7="../iconuser-lead150.svg"
        iconUserstar7="iconuserstar105.svg"
        iconFileCheck7="../iconfile-check144.svg"
        iconMessage7="iconmessage138.svg"
        iconChecklist37="iconchecklist-3138.svg"
        iconLink7="iconlink138.svg"
        iconUserLead8="../iconuser-lead151.svg"
        iconUserstar8="iconuserstar105.svg"
        iconFileCheck8="../iconfile-check145.svg"
        iconMessage8="iconmessage138.svg"
        iconChecklist38="iconchecklist-3138.svg"
        iconLink8="iconlink138.svg"
        iconUserLead9="../iconuser-lead152.svg"
        iconUserstar9="iconuserstar105.svg"
        iconFileCheck9="../iconfile-check146.svg"
        iconMessage9="iconmessage138.svg"
        iconChecklist39="iconchecklist-3138.svg"
        iconLink9="iconlink138.svg"
        iconUserLead10="../iconuser-lead153.svg"
        iconUserstar10="iconuserstar105.svg"
        iconFileCheck10="../iconfile-check147.svg"
      />
      <div className={styles.panOut}>
        <div className={styles.panOutChild} />
        <img
          className={styles.chevronDown1Icon}
          alt=""
          src="../chevrondown-1.svg"
        />
      </div>
      <div className={styles.saveFilterItem} />
      <div className={styles.saveFilter1}>
        <SavedContainer />
      </div>
      <div className={styles.colorPicker}>
        <ContainerSection />
      </div>
    </div>
  );
};

export default SaveFilter;
