import Header from "../components/header";
import SidebarContainer from "../components/sidebar-container";
import WorkflowSection from "../components/workflow-section";
import AddContainer from "../components/add-container";
import CardContainer from "../components/card-container";
import CardForm from "../components/card-form";
import CardFilter1 from "../components/card-filter1";
import ViewsContainer from "../components/views-container";
import styles from "./view-popup.module.css";

const ViewPopup = () => {
  return (
    <div className={styles.viewPopup}>
      <Header
        groupImageUrl="../group-1956.svg"
        groupImageUrl195="../group-2012.svg"
      />
      <SidebarContainer
        arrowIconUrl="../icondouble-arrow2.svg"
        dashboardIconUrl="../icondashboad6.svg"
        calendarIconUrl="../iconcalendar2.svg"
        socialMediaIconUrl="../iconsocial-media6.svg"
        analyticsIconUrl="../iconanalytic2.svg"
        dotIconUrl="../dot-01-xs-18.svg"
        userLeadIconUrl="../iconuser-lead52.svg"
        dotIcon1Url="../dot-01-xs-18.svg"
        userStarIconUrl="iconuserstar52.svg"
        notificationIconUrl="../iconnotifications2.svg"
        dotIcon1Url2="../dot-01-xs-18.svg"
        documentIconUrl="../icondocuments2.svg"
        dotIcon2Url="../dot-01-xs-18.svg"
        segmentIconUrl="../iconsegments2.svg"
        checkIconUrl="../iconfile-check148.svg"
      />
      <div className={styles.frameParent}>
        <div className={styles.groupParent}>
          <img className={styles.frameChild} alt="" src="../group-12991.svg" />
          <div className={styles.panOut}>
            <div className={styles.panOutChild} />
            <img
              className={styles.iconarrowChevron}
              alt=""
              src="../iconarrow-chevron2.svg"
            />
          </div>
        </div>
        <img className={styles.frameChild} alt="" src="../group-2025.svg" />
      </div>
      <div className={styles.groupContainer}>
        <WorkflowSection
          ellipseImageUrl="../ellipse-47.svg"
          ellipse72ImageUrl="../ellipse-72.svg"
          ellipse471ImageUrl="../ellipse-471.svg"
          iconDesignImageUrl="../icondesign3.svg"
          iconCodeImageUrl="../ellipse-72.svg"
          ellipse472ImageUrl="../ellipse-472.svg"
          iconCodeSvgUrl="../iconcode3.svg"
          ellipse72SvgUrl="../ellipse-72.svg"
          iconDesign1ImageUrl="../ellipse-471.svg"
          iconAnnouncementImageUrl="../iconannoucement2.svg"
          ellipse72SvgUrl2="../ellipse-72.svg"
          iconCode1ImageUrl="../ellipse-474@2x.png"
          ellipse472SvgUrl="../ellipse-72.svg"
          iconAnnouncementImageUrl2="../ellipse-475@2x.png"
          ellipse72SvgUrl3="../ellipse-72.svg"
          iconCode1SvgUrl="../ellipse-476@2x.png"
          ellipse72Text="../ellipse-72.svg"
          iconCode1SvgUrl2="../ellipse-477@2x.png"
          ellipse72Text2="../ellipse-72.svg"
          iconPinnedText="../iconpinned2.svg"
          group242Text="../group-2422.svg"
          iconSaveText="../iconsave5.svg"
          frameSvgUrl="../frame.svg"
        />
        <AddContainer
          sortByText="(2)"
          sortByIconUrl="../iconsort-by12.svg"
          userLeadIconUrl="../iconuser-lead155.svg"
          userStarText="iconuserstar53.svg"
          checkIconUrl="../iconfile-check149.svg"
          descriptionText="icondescription48.svg"
          messageText="iconmessage48.svg"
          checklistIconUrl="iconchecklist-348.svg"
          iconLinkText="../iconlink2.svg"
          ellipseText="../ellipse-821.svg"
          agentBookText="AgentBook"
          userLeadIconUrl2="../iconuser-lead156.svg"
          userStarText2="iconuserstar53.svg"
          checkIconUrl2="../iconfile-check150.svg"
          descriptionText2="icondescription48.svg"
          messageIconUrl="iconmessage48.svg"
          checklistIconText="iconchecklist-348.svg"
          iconLinkText2="../iconlink2.svg"
          closeText="../iconclose4.svg"
        />
        <CardContainer
          completionStatus="Completed"
          sortIconUrl="iconsort-by13.svg"
          userLeadIconUrl="../iconuser-lead157.svg"
          userStarIconUrl="iconuserstar55.svg"
          descriptionIconUrl="icondescription48.svg"
          messageIconUrl="iconmessage50.svg"
          checklistIconUrl="iconchecklist-350.svg"
          iconLinkUrl="../iconlink2.svg"
        />
        <CardForm
          statusText="In Review"
          sortIconUrl="iconsort-by13.svg"
          statusIconUrl="../ellipse-821.svg"
          teamName="AgentBook"
          userLeadIconUrl="../iconuser-lead158.svg"
          userStarIconUrl="iconuserstar56.svg"
          checkIconUrl="../iconfile-check151.svg"
          taskName="Design a website"
          iconDescriptionText="icondescription48.svg"
          messageIconUrl="iconmessage50.svg"
          checklistIconUrl="iconchecklist-350.svg"
          iconLinkUrl="../iconlink2.svg"
          ellipseIconUrl="../ellipse-82.svg"
          contactRMText="ContactRM"
          userLeadIconText="../iconuser-lead159.svg"
          userStarText="iconuserstar56.svg"
          checkIconText="../iconfile-check152.svg"
          taskDescriptionText="Design a website"
          iconDescriptionText2="icondescription48.svg"
          messageIconText="iconmessage50.svg"
          checklistIconText="iconchecklist-350.svg"
          iconLinkText="../iconlink2.svg"
          ellipseIconText="../ellipse-821.svg"
          agentBookText="AgentBook"
          userLead6Text="../iconuser-lead160.svg"
          userStarText2="iconuserstar56.svg"
          check5IconText="../iconfile-check153.svg"
          designTaskText="Design a website"
          iconDescriptionText3="icondescription48.svg"
          messageIcon2Url="iconmessage50.svg"
          checklist3IconUrl="iconchecklist-350.svg"
          iconLink2Text="../iconlink2.svg"
          contactRMText2="ContactRM"
          userLead7Text="../iconuser-lead161.svg"
          userStar4Text="iconuserstar56.svg"
          check6IconText="../iconfile-check154.svg"
          designTaskDescriptionText="Design a website"
          iconDescriptionUrl="icondescription48.svg"
          messageIcon2Text="iconmessage50.svg"
          checklist3IconText="iconchecklist-350.svg"
          iconLink2Text2="../iconlink2.svg"
          ellipseIconText2="../ellipse-821.svg"
          agentBookText2="AgentBook"
          userLead8Text="../iconuser-lead162.svg"
          userStar4Text2="iconuserstar162.svg"
          check7IconText="../iconfile-check155.svg"
          designTaskTitle="Design a website"
          iconDescriptionUrl2="../icondescription.svg"
          message2IconText="iconmessage149.svg"
          checklist3IconText2="iconchecklist-3149.svg"
          iconLink2Text3="../iconlink2.svg"
        />
        <CardForm
          statusText="To Do"
          sortIconUrl="iconsort-by13.svg"
          statusIconUrl="../ellipse-828.svg"
          teamName="DW4RTeam"
          userLeadIconUrl="../iconuser-lead163.svg"
          userStarIconUrl="iconuserstar56.svg"
          checkIconUrl="../iconfile-check156.svg"
          taskName="Design a website"
          iconDescriptionText="icondescription48.svg"
          messageIconUrl="iconmessage48.svg"
          checklistIconUrl="iconchecklist-348.svg"
          iconLinkUrl="iconlink8.svg"
          ellipseIconUrl="../ellipse-829.svg"
          contactRMText="Asteler.io"
          userLeadIconText="../iconuser-lead164.svg"
          userStarText="iconuserstar56.svg"
          checkIconText="../iconfile-check157.svg"
          taskDescriptionText="Design a website"
          iconDescriptionText2="icondescription48.svg"
          messageIconText="iconmessage48.svg"
          checklistIconText="iconchecklist-348.svg"
          iconLinkText="iconlink8.svg"
          ellipseIconText="../ellipse-82.svg"
          agentBookText="ContactRM"
          userLead6Text="../iconuser-lead165.svg"
          userStarText2="iconuserstar56.svg"
          check5IconText="../iconfile-check158.svg"
          designTaskText="Design a website"
          iconDescriptionText3="icondescription48.svg"
          messageIcon2Url="iconmessage48.svg"
          checklist3IconUrl="iconchecklist-348.svg"
          iconLink2Text="iconlink8.svg"
          contactRMText2="ContactRM"
          userLead7Text="../iconuser-lead166.svg"
          userStar4Text="iconuserstar56.svg"
          check6IconText="../iconfile-check159.svg"
          designTaskDescriptionText="Design a website"
          iconDescriptionUrl="icondescription48.svg"
          messageIcon2Text="iconmessage48.svg"
          checklist3IconText="iconchecklist-348.svg"
          iconLink2Text2="iconlink8.svg"
          ellipseIconText2="../ellipse-82.svg"
          agentBookText2="ContactRM"
          userLead8Text="../iconuser-lead167.svg"
          userStar4Text2="iconuserstar56.svg"
          check7IconText="../iconfile-check160.svg"
          designTaskTitle="Design a website"
          iconDescriptionUrl2="../icondescription.svg"
          message2IconText="iconmessage154.svg"
          checklist3IconText2="iconchecklist-3154.svg"
          iconLink2Text3="iconlink8.svg"
          propLeft="154px"
          propDisplay="unset"
          propDisplay2="flex"
          propBackgroundColor1="#deefff"
          propDisplay3="none"
          propDisplay4="flex"
          propDisplay5="flex"
          propDisplay6="flex"
          propDisplay7="none"
          propDisplay9="flex"
          propDisplay10="none"
          propDisplay11="flex"
          propDisplay12="flex"
          propDisplay13="flex"
          propDisplay14="none"
          propDisplay16="flex"
          propDisplay17="none"
          propDisplay18="flex"
          propDisplay19="flex"
          propDisplay20="flex"
          propDisplay21="unset"
          propDisplay23="flex"
          propDisplay24="none"
          propDisplay25="flex"
          propDisplay26="flex"
          propDisplay27="flex"
          propDisplay28="none"
          propDisplay29="flex"
          propDisplay30="none"
          propDisplay31="flex"
          propDisplay32="flex"
          propDisplay33="flex"
        />
        <CardFilter1
          sortIconUrl="iconsort-by13.svg"
          userLeadIconUrl="../iconuser-lead168.svg"
          userStarIconUrl="iconuserstar56.svg"
          fileCheckIconUrl="../iconfile-check161.svg"
          descriptionIconUrl="icondescription48.svg"
          messageIconUrl="iconmessage50.svg"
          checklistIconUrl="iconchecklist-350.svg"
          iconLinkUrl="iconlink8.svg"
          userLeadIconUrl15="../iconuser-lead169.svg"
          userStarIconUrl1="iconuserstar56.svg"
          fileCheck14IconUrl="../iconfile-check162.svg"
          descriptionIcon2Url="icondescription48.svg"
          message2IconUrl="iconmessage50.svg"
          checklist3IconUrl="iconchecklist-350.svg"
          iconLink8Url="iconlink8.svg"
          userLead16IconUrl="../iconuser-lead170.svg"
          userStarIconUrl12="iconuserstar56.svg"
          fileCheck15IconUrl="../iconfile-check163.svg"
          iconDescriptionUrl="icondescription48.svg"
          message2IconUrl2="iconmessage50.svg"
          checklist3IconUrl2="iconchecklist-350.svg"
          iconLink8Url2="iconlink8.svg"
          userLead17IconUrl="../iconuser-lead171.svg"
          userStarIcon1Url="iconuserstar56.svg"
          fileCheckIconUrl16="../iconfile-check164.svg"
          iconDescription2Url="icondescription48.svg"
          message2IconUrl3="iconmessage50.svg"
          checklist3IconUrl3="iconchecklist-350.svg"
          iconLink8Url3="iconlink8.svg"
          userLead18IconUrl="../iconuser-lead172.svg"
          userStar4IconUrl="iconuserstar56.svg"
          fileCheck17IconUrl="../iconfile-check165.svg"
          iconDescription2Text="icondescription48.svg"
          message2IconText="iconmessage50.svg"
          checklist3IconText="iconchecklist-350.svg"
          iconLink8Text="iconlink8.svg"
          userLead19IconText="../iconuser-lead173.svg"
          userStar4IconText="iconuserstar162.svg"
          fileCheck18IconText="../iconfile-check166.svg"
          iconDescription2Text2="../icondescription.svg"
          message2IconText2="iconmessage149.svg"
          checklist3IconText2="iconchecklist-3149.svg"
          iconLink8Text2="iconlink8.svg"
          userLead20IconText="../iconuser-lead174.svg"
          userStar4IconText2="iconuserstar162.svg"
          fileCheckIconText="../iconfile-check167.svg"
          iconDescription2Text3="../icondescription.svg"
          message2IconText3="iconmessage149.svg"
          checklist3IconText3="iconchecklist-3149.svg"
          iconLink8Text3="iconlink8.svg"
          userLead21IconText="../iconuser-lead175.svg"
          userStar4IconText3="iconuserstar162.svg"
          check20IconText="../iconfile-check168.svg"
          group371IconText="group-3712.svg"
          sortIconText="iconsort-by13.svg"
        />
      </div>
      <ViewsContainer />
    </div>
  );
};

export default ViewPopup;
