import Header from "../components/header";
import ZaanCorpContainer from "../components/zaan-corp-container";
import WorkflowSection from "../components/workflow-section";
import AddContainer from "../components/add-container";
import CardContainer from "../components/card-container";
import CardForm from "../components/card-form";
import CardFilter1 from "../components/card-filter1";
import styles from "./workflow.module.css";

const Workflow = () => {
  return (
    <div className={styles.workflow}>
      <Header
        groupImageUrl="../group-19512.svg"
        groupImageUrl195="../group-20111.svg"
      />
      <div className={styles.sidebar}>
        <ZaanCorpContainer />
      </div>
      <div className={styles.frameParent}>
        <div className={styles.groupParent}>
          <img className={styles.frameChild} alt="" src="../group-1299.svg" />
          <div className={styles.panOut}>
            <div className={styles.panOutChild} />
            <img
              className={styles.iconarrowChevron}
              alt=""
              src="../iconarrow-chevron2.svg"
            />
          </div>
        </div>
        <img className={styles.frameItem} alt="" src="../group-202.svg" />
      </div>
      <div className={styles.groupContainer}>
        <WorkflowSection
          ellipseImageUrl="../ellipse-47.svg"
          ellipse72ImageUrl="../ellipse-72.svg"
          ellipse471ImageUrl="../ellipse-471.svg"
          iconDesignImageUrl="../icondesign8.svg"
          iconCodeImageUrl="../ellipse-72.svg"
          ellipse472ImageUrl="../ellipse-472.svg"
          iconCodeSvgUrl="../iconcode8.svg"
          ellipse72SvgUrl="../ellipse-72.svg"
          iconDesign1ImageUrl="../ellipse-471.svg"
          iconAnnouncementImageUrl="iconannoucement8.svg"
          ellipse72SvgUrl2="../ellipse-72.svg"
          iconCode1ImageUrl="../ellipse-474@2x.png"
          ellipse472SvgUrl="../ellipse-72.svg"
          iconAnnouncementImageUrl2="../ellipse-475@2x.png"
          ellipse72SvgUrl3="../ellipse-72.svg"
          iconCode1SvgUrl="../ellipse-476@2x.png"
          ellipse72Text="../ellipse-72.svg"
          iconCode1SvgUrl2="../ellipse-477@2x.png"
          ellipse72Text2="../ellipse-72.svg"
          iconPinnedText="../iconpinned10.svg"
          group242Text="../group-24211.svg"
          iconSaveText="../iconsave12.svg"
          frameSvgUrl="../frame.svg"
        />
        <AddContainer
          sortByText="(2)"
          sortByIconUrl="iconsort-by71.svg"
          userLeadIconUrl="../iconuser-lead290.svg"
          userStarText="iconuserstar220.svg"
          checkIconUrl="../iconfile-check279.svg"
          descriptionText="icondescription48.svg"
          messageText="iconmessage197.svg"
          checklistIconUrl="iconchecklist-3197.svg"
          iconLinkText="../iconlink.svg"
          ellipseText="../ellipse-821.svg"
          agentBookText="AgentBook"
          userLeadIconUrl2="../iconuser-lead291.svg"
          userStarText2="iconuserstar220.svg"
          checkIconUrl2="../iconfile-check280.svg"
          descriptionText2="icondescription48.svg"
          messageIconUrl="iconmessage197.svg"
          checklistIconText="iconchecklist-3197.svg"
          iconLinkText2="../iconlink.svg"
          closeText="iconclose12.svg"
        />
        <CardContainer
          completionStatus="Completed"
          sortIconUrl="../iconsort-by72.svg"
          descriptionIconUrl="icondescription48.svg"
          messageIconUrl="iconmessage243.svg"
          checklistIconUrl="iconchecklist-3243.svg"
          iconLinkUrl="iconlink26.svg"
        />
        <CardForm
          statusText="In Review"
          sortIconUrl="iconsort-by73.svg"
          statusIconUrl="../ellipse-821.svg"
          teamName="AgentBook"
          userLeadIconUrl="../iconuser-lead292.svg"
          userStarIconUrl="iconuserstar271.svg"
          checkIconUrl="../iconfile-check281.svg"
          taskName="Design a website"
          iconDescriptionText="icondescription48.svg"
          messageIconUrl="iconmessage264.svg"
          checklistIconUrl="iconchecklist-3244.svg"
          iconLinkUrl="../iconlink.svg"
          ellipseIconUrl="../ellipse-82.svg"
          contactRMText="ContactRM"
          userLeadIconText="../iconuser-lead293.svg"
          userStarText="iconuserstar271.svg"
          checkIconText="../iconfile-check282.svg"
          taskDescriptionText="Design a website"
          iconDescriptionText2="icondescription48.svg"
          messageIconText="iconmessage264.svg"
          checklistIconText="iconchecklist-3244.svg"
          iconLinkText="../iconlink.svg"
          ellipseIconText="../ellipse-821.svg"
          agentBookText="AgentBook"
          userLead6Text="../iconuser-lead294.svg"
          userStarText2="iconuserstar271.svg"
          check5IconText="../iconfile-check283.svg"
          designTaskText="Design a website"
          iconDescriptionText3="icondescription48.svg"
          messageIcon2Url="iconmessage264.svg"
          checklist3IconUrl="iconchecklist-3244.svg"
          iconLink2Text="../iconlink.svg"
          contactRMText2="ContactRM"
          userLead7Text="../iconuser-lead295.svg"
          userStar4Text="iconuserstar271.svg"
          check6IconText="../iconfile-check284.svg"
          designTaskDescriptionText="Design a website"
          iconDescriptionUrl="icondescription48.svg"
          messageIcon2Text="iconmessage264.svg"
          checklist3IconText="iconchecklist-3244.svg"
          iconLink2Text2="../iconlink.svg"
          ellipseIconText2="../ellipse-821.svg"
          agentBookText2="AgentBook"
          userLead8Text="../iconuser-lead296.svg"
          userStar4Text2="iconuserstar271.svg"
          check7IconText="../iconfile-check285.svg"
          designTaskTitle="Design a website"
          iconDescriptionUrl2="icondescription48.svg"
          message2IconText="iconmessage264.svg"
          checklist3IconText2="iconchecklist-3244.svg"
          iconLink2Text3="../iconlink.svg"
        />
        <CardForm
          statusText="To Do"
          sortIconUrl="iconsort-by74.svg"
          statusIconUrl="../ellipse-828.svg"
          teamName="DW4RTeam"
          userLeadIconUrl="../iconuser-lead297.svg"
          userStarIconUrl="iconuserstar220.svg"
          checkIconUrl="../iconfile-check286.svg"
          taskName="Design a website"
          iconDescriptionText="icondescription48.svg"
          messageIconUrl="iconmessage197.svg"
          checklistIconUrl="iconchecklist-3197.svg"
          iconLinkUrl="../iconlink.svg"
          ellipseIconUrl="../ellipse-829.svg"
          contactRMText="Asteler.io"
          userLeadIconText="../iconuser-lead298.svg"
          userStarText="iconuserstar220.svg"
          checkIconText="../iconfile-check287.svg"
          taskDescriptionText="Design a website"
          iconDescriptionText2="icondescription48.svg"
          messageIconText="iconmessage197.svg"
          checklistIconText="iconchecklist-3197.svg"
          iconLinkText="../iconlink.svg"
          ellipseIconText="../ellipse-82.svg"
          agentBookText="ContactRM"
          userLead6Text="../iconuser-lead299.svg"
          userStarText2="iconuserstar220.svg"
          check5IconText="../iconfile-check288.svg"
          designTaskText="Design a website"
          iconDescriptionText3="icondescription48.svg"
          messageIcon2Url="iconmessage197.svg"
          checklist3IconUrl="iconchecklist-3197.svg"
          iconLink2Text="../iconlink.svg"
          contactRMText2="ContactRM"
          userLead7Text="../iconuser-lead300.svg"
          userStar4Text="iconuserstar220.svg"
          check6IconText="../iconfile-check289.svg"
          designTaskDescriptionText="Design a website"
          iconDescriptionUrl="icondescription48.svg"
          messageIcon2Text="iconmessage197.svg"
          checklist3IconText="iconchecklist-3197.svg"
          iconLink2Text2="../iconlink.svg"
          ellipseIconText2="../ellipse-82.svg"
          agentBookText2="ContactRM"
          userLead8Text="../iconuser-lead301.svg"
          userStar4Text2="iconuserstar220.svg"
          check7IconText="../iconfile-check290.svg"
          designTaskTitle="Design a website"
          iconDescriptionUrl2="icondescription48.svg"
          message2IconText="iconmessage197.svg"
          checklist3IconText2="iconchecklist-3197.svg"
          iconLink2Text3="iconlink32.svg"
          propLeft="154px"
          propDisplay="unset"
          propDisplay2="flex"
          propBackgroundColor1="#deefff"
          propDisplay3="none"
          propDisplay4="flex"
          propDisplay5="flex"
          propDisplay6="flex"
          propDisplay7="none"
          propDisplay9="flex"
          propDisplay10="none"
          propDisplay11="flex"
          propDisplay12="flex"
          propDisplay13="flex"
          propDisplay14="none"
          propDisplay16="flex"
          propDisplay17="none"
          propDisplay18="flex"
          propDisplay19="flex"
          propDisplay20="flex"
          propDisplay21="unset"
          propDisplay23="flex"
          propDisplay24="none"
          propDisplay25="flex"
          propDisplay26="flex"
          propDisplay27="flex"
          propDisplay28="none"
          propDisplay29="flex"
          propDisplay30="none"
          propDisplay31="flex"
          propDisplay32="flex"
          propDisplay33="flex"
        />
        <CardFilter1
          sortIconUrl="../iconsort-by69.svg"
          userLeadIconUrl="../iconuser-lead302.svg"
          userStarIconUrl="iconuserstar220.svg"
          fileCheckIconUrl="../iconfile-check291.svg"
          descriptionIconUrl="icondescription48.svg"
          messageIconUrl="iconmessage244.svg"
          checklistIconUrl="iconchecklist-3244.svg"
          iconLinkUrl="iconlink32.svg"
          userLeadIconUrl15="../iconuser-lead303.svg"
          userStarIconUrl1="iconuserstar220.svg"
          fileCheck14IconUrl="../iconfile-check292.svg"
          descriptionIcon2Url="icondescription48.svg"
          message2IconUrl="iconmessage244.svg"
          checklist3IconUrl="iconchecklist-3244.svg"
          iconLink8Url="iconlink32.svg"
          userLead16IconUrl="../iconuser-lead304.svg"
          userStarIconUrl12="iconuserstar220.svg"
          fileCheck15IconUrl="../iconfile-check293.svg"
          iconDescriptionUrl="icondescription48.svg"
          message2IconUrl2="iconmessage244.svg"
          checklist3IconUrl2="iconchecklist-3244.svg"
          iconLink8Url2="iconlink32.svg"
          userLead17IconUrl="../iconuser-lead305.svg"
          userStarIcon1Url="iconuserstar220.svg"
          fileCheckIconUrl16="../iconfile-check294.svg"
          iconDescription2Url="icondescription48.svg"
          message2IconUrl3="iconmessage244.svg"
          checklist3IconUrl3="iconchecklist-3244.svg"
          iconLink8Url3="iconlink32.svg"
          userLead18IconUrl="../iconuser-lead306.svg"
          userStar4IconUrl="iconuserstar220.svg"
          fileCheck17IconUrl="../iconfile-check295.svg"
          iconDescription2Text="icondescription48.svg"
          message2IconText="iconmessage244.svg"
          checklist3IconText="iconchecklist-3244.svg"
          iconLink8Text="iconlink32.svg"
          userLead19IconText="../iconuser-lead307.svg"
          userStar4IconText="iconuserstar220.svg"
          fileCheck18IconText="../iconfile-check296.svg"
          iconDescription2Text2="icondescription48.svg"
          message2IconText2="iconmessage244.svg"
          checklist3IconText2="iconchecklist-3244.svg"
          iconLink8Text2="iconlink32.svg"
          userLead20IconText="../iconuser-lead308.svg"
          userStar4IconText2="iconuserstar220.svg"
          fileCheckIconText="../iconfile-check297.svg"
          iconDescription2Text3="icondescription48.svg"
          message2IconText3="iconmessage244.svg"
          checklist3IconText3="iconchecklist-3244.svg"
          iconLink8Text3="iconlink32.svg"
          userLead21IconText="../iconuser-lead309.svg"
          userStar4IconText3="iconuserstar220.svg"
          check20IconText="../iconfile-check298.svg"
          group371IconText="../group-371.svg"
          sortIconText="../iconsort-by69.svg"
        />
      </div>
    </div>
  );
};

export default Workflow;
